"""
Django settings for quran_hadith_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv # Import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env') # Call load_dotenv() early, pointing to your .env file

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'a_weak_default_secret_key_for_dev_only_if_not_in_env')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quran_app',
    'hadith_app',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quran_hadith_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')], # For base.html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quran_hadith_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta' # Set your timezone
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core', 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_prod') # For production

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# KEMENAG_BASE_URL = os.environ.get('KEMENAG_BASE_URL', 'https://quran-api.lpmqkemenag.go.id/v1') # e.g., https://quran-api.lpmqkemenag.go.id/v1
# KEMENAG_API_KEY = os.environ.get('KEMENAG_API_KEY') # If needed
EQURAN_API_BASE_URL = os.environ.get('EQURAN_API_BASE_URL')
HADITH_API_BASE_URL = os.environ.get('HADITH_API_BASE_URL', 'https://api.hadith.gading.dev')

GEMINI_PROJECT_ID = os.environ.get('GEMINI_PROJECT_ID')
GEMINI_LOCATION = os.environ.get('GEMINI_LOCATION')

PRAYER_TIMES_API_BASE_URL = os.environ.get('PRAYER_TIMES_API_BASE_URL')
PRAYER_TIMES_CITY = os.environ.get('PRAYER_TIMES_CITY')
PRAYER_TIMES_COUNTRY = os.environ.get('PRAYER_TIMES_COUNTRY')
PRAYER_TIMES_METHOD = os.environ.get('PRAYER_TIMES_METHOD')
HADITH_API_EDITIONS_URL = os.environ.get('HADITH_API_EDITIONS_URL')
HADITH_API_EDITION_BASE_URL = os.environ.get('HADITH_API_EDITION_BASE_URL')
