# Generated by Django 5.2.1 on 2025-05-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name_simple', models.CharField(max_length=100)),
                ('name_arabic', models.CharField(max_length=100)),
                ('revelation_place', models.CharField(max_length=20)),
                ('verses_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_surah', models.IntegerField()),
                ('text_uthmani', models.TextField()),
                ('translation_id', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran_app.surah')),
            ],
            options={
                'unique_together': {('surah', 'number_in_surah')},
            },
        ),
    ]
